services:
  backend:
    build:
      context: ./QuizAppBackend
      dockerfile: Dockerfile
    container_name: QuizAppBackend
    ports:
      - "8080:8080"
    volumes:
      - ./QuizAppBackend/Data/quiz.db:/app/data/quiz.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    restart: unless-stopped

  frontend:
    build:
      context: ./QuizAppFrontend
      dockerfile: Dockerfile
    container_name: QuizAppFrontend
    ports:
      - "80:80"

    restart: unless-stopped
